spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: "authguard-user-public-service"
            uri: lb://AUTHGUARD-USER-SERVICE
            predicates:
            - Path=/api/v1/auth/user/**
            filters:
                - StripPrefix=2
                - UserFilter
          - id: "authguard-user-private-service"
            uri: lb://AUTHGUARD-USER-SERVICE
            predicates:
              - Path=/api/v1/user/**
            filters:
                - StripPrefix=2
                - UserFilter
                - name: AuthenticationFilter
                  args:
                    enabled: true
          - id: "authguard-app-service"
            uri: lb://AUTHGUARD-APP-SERVICE  
            predicates:
            - Path=/api/v1/apps/**
            filters:
            - StripPrefix=2
            - name : AuthenticationFilter
              args:
                enabled: true
          - id : "authguard-client-public-service"
            uri: lb://AUTHGUARD-CLIENT-SERVICE
            predicates:
            - Path=/api/v1/auth/client/**
            filters:
            - StripPrefix=3
          - id : "authguard-client-service"
            uri: lb://AUTHGUARD-CLIENT-SERVICE
            predicates:
            - Path=/api/v1/client/**
            filters:
            - StripPrefix=2
            - name: AuthenticationFilter
              args:
                enabled: true


      